exchange:
  exchange_name: standx
  private_key: ""
  chain: bsc

symbol: BTC-USD

grid:
  upper_price: 100000
  lower_price: 90000
  price_step: 20
  grid_count: 5
  price_spread: 200
  order_quantity: 0.0001
  sleep_interval: 5

risk:
  enable: true
  adx_threshold: 25
  adx_max: 60

cancel_stale_orders:
  enable: false
  stale_seconds: 5
  cancel_probability: 0.5